version: '3.7'
services:
  db:
    image: postgres:10.10
    restart: always
    environment:
      PGDATA: /var/lib/postgres/data/pgdata
      TZ: "Asia/Tokyo"
    volumes:
      - postgresql_data:/var/lib/postgres/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgresql_data:
    driver: local
